### ISSUE TITLE
#4560 UI/UX - display comments on ideas

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/zt-app#98]
**user:** *moderator/ initiator/ participants*
**device & browser:** *Android Emulator*
**Comment/Question:** *Hey, I finally managed to restart my emulator and see the comments and there is a small thing, the ballon icon had a different purpose on a+, currently when you click on the ballon it shows this Notiz thing which I never understood why we have that. Shall we do that in the app as well? @hello-kathi @lthueer ? Otherwise I would just display the comments directly below the ideas, so users don't have to click to see the comments.* 
 
![Screenshot 2021-08-18 at 15 21 23](https://user-images.githubusercontent.com/59610786/129906419-d3dd8bb5-beeb-4eb0-91c8-101c59e1dad0.png)
* 
![Screenshot 2021-08-18 at 15 21 38](https://user-images.githubusercontent.com/59610786/129905913-7e25da6a-379d-4768-8cc9-d3971a405109.png)

**Comment by lthueer** [comment]
@mcastro-lqd I think this is a functionality for moderators. As we develop the app primarily for participants, I would say we don't need it in the app. From my point of view it would be best, if the comments are directly displayed below the idea, so that no click on the ballon is needed. What do you think @hello-kathi ?

**Comment by hello-kathi** [comment]
I think the same way @lthueer Thank you @mcastro-lqd for pointing it out!
